# Generated by Django 2.1.7 on 2024-09-16 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240916_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 16, 17, 36, 52, 260455)),
        ),
    ]
